//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.08 at 05:32:24 PM CST 
//


package com.demo.demo_jaxb.demo_package;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for demoClassName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="demoClassName"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="demoString" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="demoByte" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "demoClassName", propOrder = {
    "demoString",
    "demoByte"
})
public class DemoClassName {

    @XmlElement(required = true)
    protected String demoString;
    protected byte demoByte;

    /**
     * Gets the value of the demoString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDemoString() {
        return demoString;
    }

    /**
     * Sets the value of the demoString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDemoString(String value) {
        this.demoString = value;
    }

    /**
     * Gets the value of the demoByte property.
     * 
     */
    public byte getDemoByte() {
        return demoByte;
    }

    /**
     * Sets the value of the demoByte property.
     * 
     */
    public void setDemoByte(byte value) {
        this.demoByte = value;
    }

}
