//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.08 at 05:32:24 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.demo.com/demo_JAXB/demo_Package")
package com.demo.demo_jaxb.demo_package;
